version: '2'
volumes:
  # volume to store mysql database data  
  data_sql:   
services:
    Memcached:
      image: sameersbn/memcached:1.5.6
      ports:
        - 11211:11211
#      restart: always

    docker-mysql:
      image: mysql
#      command: --default-authentication-plugin=mysql_native_password
      #restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_PASSWORD: example
        MYSQL_DATABASE: sessionMngr
      ports:
        - 3307:3306     


    