spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3307/sessionMngr?autoReconnect=true
    username: root
    password: example
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: create
    show-sql: true
  server:
    port: 
      8443
    ssl:
      enabled:
        true  
      key-store: /resources/certificate.pfx
      key-store-password: panathinaikos
      key-store-type: PKCS12
    http:
      port:
        8080
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
  server:
    port: 
      8443
    ssl:
      enabled:
        true  
      key-store: /resources/certificate.pfx
      key-store-password: panathinaikos
      key-store-type: PKCS12
    http:
      port:
        8080